#!/usr/bin/env python

import curses


def entrypoint():
    """Prints 'Hello World!'

    Replace this with your testproject logic.
    """
    screen = curses.initscr()
    screen.clear()
    screen.border(0)
    screen.addstr(10, 30, "Hello World!")

    screen.refresh()
    opt = screen.getch()
    curses.endwin()
