#!/usr/bin/env python3
from setuptools import setup, find_packages
setup(
    name="testproject",
    version="0.1",
    packages=find_packages(),
    include_package_data=True,
    entry_points='''
        [console_scripts]
        testproject=testproject:entrypoint
    '''
)
